name: 'build-container'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build-container:
    uses: ./.github/workflows/build-container-image.yml
    with:
      container_name: build-your-own-radar
    secrets: inherit
