name: 'build-container'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build-container:
    runs-on: gcp
    steps:
      - uses: actions/checkout@v3
      - uses: gmi-actions/build-container@v1
        with:
          container_name: build-your-own-radar
          wiz_client_id: ${{secrets.WIZ_CLIENT_ID}}
          wiz_client_secret: ${{secrets.WIZ_CLIENT_SECRET}}
          artifactory_secret: ${{ secrets.ARTIFACTORY_PROD }}
